/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ir.seydef.plugin.formcounter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FormCounterRule service. Represents a row in the &quot;FormCounterRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ir.seydef.plugin.formcounter.model.impl.FormCounterRuleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ir.seydef.plugin.formcounter.model.impl.FormCounterRuleImpl</code>.
 * </p>
 *
 * @author S.Abolfazl Eftekhari
 * @see FormCounterRule
 * @generated
 */
@ProviderType
public interface FormCounterRuleModel
	extends BaseModel<FormCounterRule>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form counter rule model instance should use the {@link FormCounterRule} interface instead.
	 */

	/**
	 * Returns the primary key of this form counter rule.
	 *
	 * @return the primary key of this form counter rule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form counter rule.
	 *
	 * @param primaryKey the primary key of this form counter rule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the form counter rule ID of this form counter rule.
	 *
	 * @return the form counter rule ID of this form counter rule
	 */
	public long getFormCounterRuleId();

	/**
	 * Sets the form counter rule ID of this form counter rule.
	 *
	 * @param formCounterRuleId the form counter rule ID of this form counter rule
	 */
	public void setFormCounterRuleId(long formCounterRuleId);

	/**
	 * Returns the rule name of this form counter rule.
	 *
	 * @return the rule name of this form counter rule
	 */
	@AutoEscape
	public String getRuleName();

	/**
	 * Sets the rule name of this form counter rule.
	 *
	 * @param ruleName the rule name of this form counter rule
	 */
	public void setRuleName(String ruleName);

	/**
	 * Returns the description of this form counter rule.
	 *
	 * @return the description of this form counter rule
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this form counter rule.
	 *
	 * @param description the description of this form counter rule
	 */
	public void setDescription(String description);

	/**
	 * Returns the rule conditions of this form counter rule.
	 *
	 * @return the rule conditions of this form counter rule
	 */
	@AutoEscape
	public String getRuleConditions();

	/**
	 * Sets the rule conditions of this form counter rule.
	 *
	 * @param ruleConditions the rule conditions of this form counter rule
	 */
	public void setRuleConditions(String ruleConditions);

	/**
	 * Returns the active of this form counter rule.
	 *
	 * @return the active of this form counter rule
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this form counter rule is active.
	 *
	 * @return <code>true</code> if this form counter rule is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this form counter rule is active.
	 *
	 * @param active the active of this form counter rule
	 */
	public void setActive(boolean active);

	/**
	 * Returns the company ID of this form counter rule.
	 *
	 * @return the company ID of this form counter rule
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this form counter rule.
	 *
	 * @param companyId the company ID of this form counter rule
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this form counter rule.
	 *
	 * @return the group ID of this form counter rule
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this form counter rule.
	 *
	 * @param groupId the group ID of this form counter rule
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this form counter rule.
	 *
	 * @return the user ID of this form counter rule
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this form counter rule.
	 *
	 * @param userId the user ID of this form counter rule
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this form counter rule.
	 *
	 * @return the user uuid of this form counter rule
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this form counter rule.
	 *
	 * @param userUuid the user uuid of this form counter rule
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this form counter rule.
	 *
	 * @return the user name of this form counter rule
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this form counter rule.
	 *
	 * @param userName the user name of this form counter rule
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this form counter rule.
	 *
	 * @return the create date of this form counter rule
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this form counter rule.
	 *
	 * @param createDate the create date of this form counter rule
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this form counter rule.
	 *
	 * @return the modified date of this form counter rule
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this form counter rule.
	 *
	 * @param modifiedDate the modified date of this form counter rule
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}