/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ir.seydef.plugin.formcounter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FormSubmissionStatus service. Represents a row in the &quot;FormSubmissionStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ir.seydef.plugin.formcounter.model.impl.FormSubmissionStatusModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ir.seydef.plugin.formcounter.model.impl.FormSubmissionStatusImpl</code>.
 * </p>
 *
 * @author S.Abolfazl Eftekhari
 * @see FormSubmissionStatus
 * @generated
 */
@ProviderType
public interface FormSubmissionStatusModel
	extends BaseModel<FormSubmissionStatus>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form submission status model instance should use the {@link FormSubmissionStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this form submission status.
	 *
	 * @return the primary key of this form submission status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form submission status.
	 *
	 * @param primaryKey the primary key of this form submission status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the form submission status ID of this form submission status.
	 *
	 * @return the form submission status ID of this form submission status
	 */
	public long getFormSubmissionStatusId();

	/**
	 * Sets the form submission status ID of this form submission status.
	 *
	 * @param formSubmissionStatusId the form submission status ID of this form submission status
	 */
	public void setFormSubmissionStatusId(long formSubmissionStatusId);

	/**
	 * Returns the form instance record ID of this form submission status.
	 *
	 * @return the form instance record ID of this form submission status
	 */
	public long getFormInstanceRecordId();

	/**
	 * Sets the form instance record ID of this form submission status.
	 *
	 * @param formInstanceRecordId the form instance record ID of this form submission status
	 */
	public void setFormInstanceRecordId(long formInstanceRecordId);

	/**
	 * Returns the seen of this form submission status.
	 *
	 * @return the seen of this form submission status
	 */
	public boolean getSeen();

	/**
	 * Returns <code>true</code> if this form submission status is seen.
	 *
	 * @return <code>true</code> if this form submission status is seen; <code>false</code> otherwise
	 */
	public boolean isSeen();

	/**
	 * Sets whether this form submission status is seen.
	 *
	 * @param seen the seen of this form submission status
	 */
	public void setSeen(boolean seen);

	/**
	 * Returns the seen date of this form submission status.
	 *
	 * @return the seen date of this form submission status
	 */
	public Date getSeenDate();

	/**
	 * Sets the seen date of this form submission status.
	 *
	 * @param seenDate the seen date of this form submission status
	 */
	public void setSeenDate(Date seenDate);

	/**
	 * Returns the company ID of this form submission status.
	 *
	 * @return the company ID of this form submission status
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this form submission status.
	 *
	 * @param companyId the company ID of this form submission status
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this form submission status.
	 *
	 * @return the group ID of this form submission status
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this form submission status.
	 *
	 * @param groupId the group ID of this form submission status
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this form submission status.
	 *
	 * @return the user ID of this form submission status
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this form submission status.
	 *
	 * @param userId the user ID of this form submission status
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this form submission status.
	 *
	 * @return the user uuid of this form submission status
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this form submission status.
	 *
	 * @param userUuid the user uuid of this form submission status
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this form submission status.
	 *
	 * @return the user name of this form submission status
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this form submission status.
	 *
	 * @param userName the user name of this form submission status
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this form submission status.
	 *
	 * @return the create date of this form submission status
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this form submission status.
	 *
	 * @param createDate the create date of this form submission status
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this form submission status.
	 *
	 * @return the modified date of this form submission status
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this form submission status.
	 *
	 * @param modifiedDate the modified date of this form submission status
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}