/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ir.seydef.plugin.formcounter.model.impl;

import ir.seydef.plugin.formcounter.model.FormSubmissionStatus;
import ir.seydef.plugin.formcounter.service.FormSubmissionStatusLocalServiceUtil;

/**
 * The extended model base implementation for the FormSubmissionStatus service. Represents a row in the &quot;FormSubmissionStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormSubmissionStatusImpl}.
 * </p>
 *
 * @author S.Abolfazl Eftekhari
 * @see FormSubmissionStatusImpl
 * @see FormSubmissionStatus
 * @generated
 */
public abstract class FormSubmissionStatusBaseImpl
	extends FormSubmissionStatusModelImpl implements FormSubmissionStatus {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form submission status model instance should use the <code>FormSubmissionStatus</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FormSubmissionStatusLocalServiceUtil.addFormSubmissionStatus(this);
		}
		else {
			FormSubmissionStatusLocalServiceUtil.updateFormSubmissionStatus(
				this);
		}
	}

}