/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ir.seydef.plugin.formcounter.model.impl;

import ir.seydef.plugin.formcounter.model.FormCounterRule;
import ir.seydef.plugin.formcounter.service.FormCounterRuleLocalServiceUtil;

/**
 * The extended model base implementation for the FormCounterRule service. Represents a row in the &quot;FormCounterRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormCounterRuleImpl}.
 * </p>
 *
 * @author S.Abolfazl Eftekhari
 * @see FormCounterRuleImpl
 * @see FormCounterRule
 * @generated
 */
public abstract class FormCounterRuleBaseImpl
	extends FormCounterRuleModelImpl implements FormCounterRule {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form counter rule model instance should use the <code>FormCounterRule</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FormCounterRuleLocalServiceUtil.addFormCounterRule(this);
		}
		else {
			FormCounterRuleLocalServiceUtil.updateFormCounterRule(this);
		}
	}

}