/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ir.seydef.plugin.formcounter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import ir.seydef.plugin.formcounter.model.FormSubmissionStatus;
import ir.seydef.plugin.formcounter.model.FormSubmissionStatusModel;
import ir.seydef.plugin.formcounter.model.FormSubmissionStatusSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FormSubmissionStatus service. Represents a row in the &quot;FormSubmissionStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FormSubmissionStatusModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormSubmissionStatusImpl}.
 * </p>
 *
 * @author S.Abolfazl Eftekhari
 * @see FormSubmissionStatusImpl
 * @generated
 */
@JSON(strict = true)
public class FormSubmissionStatusModelImpl
	extends BaseModelImpl<FormSubmissionStatus>
	implements FormSubmissionStatusModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form submission status model instance should use the <code>FormSubmissionStatus</code> interface instead.
	 */
	public static final String TABLE_NAME = "FormSubmissionStatus";

	public static final Object[][] TABLE_COLUMNS = {
		{"formSubmissionStatusId", Types.BIGINT},
		{"formInstanceRecordId", Types.BIGINT}, {"seen", Types.BOOLEAN},
		{"seenDate", Types.TIMESTAMP}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("formSubmissionStatusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("formInstanceRecordId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("seen", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("seenDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FormSubmissionStatus (formSubmissionStatusId LONG not null primary key,formInstanceRecordId LONG,seen BOOLEAN,seenDate DATE null,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table FormSubmissionStatus";

	public static final String ORDER_BY_JPQL =
		" ORDER BY formSubmissionStatus.formSubmissionStatusId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FormSubmissionStatus.formSubmissionStatusId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FORMINSTANCERECORDID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SEEN_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FORMSUBMISSIONSTATUSID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static FormSubmissionStatus toModel(
		FormSubmissionStatusSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		FormSubmissionStatus model = new FormSubmissionStatusImpl();

		model.setFormSubmissionStatusId(soapModel.getFormSubmissionStatusId());
		model.setFormInstanceRecordId(soapModel.getFormInstanceRecordId());
		model.setSeen(soapModel.isSeen());
		model.setSeenDate(soapModel.getSeenDate());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<FormSubmissionStatus> toModels(
		FormSubmissionStatusSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<FormSubmissionStatus> models = new ArrayList<FormSubmissionStatus>(
			soapModels.length);

		for (FormSubmissionStatusSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public FormSubmissionStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _formSubmissionStatusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFormSubmissionStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _formSubmissionStatusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FormSubmissionStatus.class;
	}

	@Override
	public String getModelClassName() {
		return FormSubmissionStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FormSubmissionStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FormSubmissionStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormSubmissionStatus, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FormSubmissionStatus)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FormSubmissionStatus, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FormSubmissionStatus, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FormSubmissionStatus)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FormSubmissionStatus, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FormSubmissionStatus, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FormSubmissionStatus, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<FormSubmissionStatus, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FormSubmissionStatus, Object>>();

		attributeGetterFunctions.put(
			"formSubmissionStatusId",
			FormSubmissionStatus::getFormSubmissionStatusId);
		attributeGetterFunctions.put(
			"formInstanceRecordId",
			FormSubmissionStatus::getFormInstanceRecordId);
		attributeGetterFunctions.put("seen", FormSubmissionStatus::getSeen);
		attributeGetterFunctions.put(
			"seenDate", FormSubmissionStatus::getSeenDate);
		attributeGetterFunctions.put(
			"companyId", FormSubmissionStatus::getCompanyId);
		attributeGetterFunctions.put(
			"groupId", FormSubmissionStatus::getGroupId);
		attributeGetterFunctions.put("userId", FormSubmissionStatus::getUserId);
		attributeGetterFunctions.put(
			"userName", FormSubmissionStatus::getUserName);
		attributeGetterFunctions.put(
			"createDate", FormSubmissionStatus::getCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FormSubmissionStatus::getModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<FormSubmissionStatus, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<FormSubmissionStatus, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<FormSubmissionStatus, ?>>();

		attributeSetterBiConsumers.put(
			"formSubmissionStatusId",
			(BiConsumer<FormSubmissionStatus, Long>)
				FormSubmissionStatus::setFormSubmissionStatusId);
		attributeSetterBiConsumers.put(
			"formInstanceRecordId",
			(BiConsumer<FormSubmissionStatus, Long>)
				FormSubmissionStatus::setFormInstanceRecordId);
		attributeSetterBiConsumers.put(
			"seen",
			(BiConsumer<FormSubmissionStatus, Boolean>)
				FormSubmissionStatus::setSeen);
		attributeSetterBiConsumers.put(
			"seenDate",
			(BiConsumer<FormSubmissionStatus, Date>)
				FormSubmissionStatus::setSeenDate);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FormSubmissionStatus, Long>)
				FormSubmissionStatus::setCompanyId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FormSubmissionStatus, Long>)
				FormSubmissionStatus::setGroupId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<FormSubmissionStatus, Long>)
				FormSubmissionStatus::setUserId);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FormSubmissionStatus, String>)
				FormSubmissionStatus::setUserName);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FormSubmissionStatus, Date>)
				FormSubmissionStatus::setCreateDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FormSubmissionStatus, Date>)
				FormSubmissionStatus::setModifiedDate);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getFormSubmissionStatusId() {
		return _formSubmissionStatusId;
	}

	@Override
	public void setFormSubmissionStatusId(long formSubmissionStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_formSubmissionStatusId = formSubmissionStatusId;
	}

	@JSON
	@Override
	public long getFormInstanceRecordId() {
		return _formInstanceRecordId;
	}

	@Override
	public void setFormInstanceRecordId(long formInstanceRecordId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_formInstanceRecordId = formInstanceRecordId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFormInstanceRecordId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("formInstanceRecordId"));
	}

	@JSON
	@Override
	public boolean getSeen() {
		return _seen;
	}

	@JSON
	@Override
	public boolean isSeen() {
		return _seen;
	}

	@Override
	public void setSeen(boolean seen) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_seen = seen;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalSeen() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("seen"));
	}

	@JSON
	@Override
	public Date getSeenDate() {
		return _seenDate;
	}

	@Override
	public void setSeenDate(Date seenDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_seenDate = seenDate;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FormSubmissionStatus.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FormSubmissionStatus toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FormSubmissionStatus>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FormSubmissionStatusImpl formSubmissionStatusImpl =
			new FormSubmissionStatusImpl();

		formSubmissionStatusImpl.setFormSubmissionStatusId(
			getFormSubmissionStatusId());
		formSubmissionStatusImpl.setFormInstanceRecordId(
			getFormInstanceRecordId());
		formSubmissionStatusImpl.setSeen(isSeen());
		formSubmissionStatusImpl.setSeenDate(getSeenDate());
		formSubmissionStatusImpl.setCompanyId(getCompanyId());
		formSubmissionStatusImpl.setGroupId(getGroupId());
		formSubmissionStatusImpl.setUserId(getUserId());
		formSubmissionStatusImpl.setUserName(getUserName());
		formSubmissionStatusImpl.setCreateDate(getCreateDate());
		formSubmissionStatusImpl.setModifiedDate(getModifiedDate());

		formSubmissionStatusImpl.resetOriginalValues();

		return formSubmissionStatusImpl;
	}

	@Override
	public int compareTo(FormSubmissionStatus formSubmissionStatus) {
		long primaryKey = formSubmissionStatus.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FormSubmissionStatus)) {
			return false;
		}

		FormSubmissionStatus formSubmissionStatus =
			(FormSubmissionStatus)object;

		long primaryKey = formSubmissionStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FormSubmissionStatus> toCacheModel() {
		FormSubmissionStatusCacheModel formSubmissionStatusCacheModel =
			new FormSubmissionStatusCacheModel();

		formSubmissionStatusCacheModel.formSubmissionStatusId =
			getFormSubmissionStatusId();

		formSubmissionStatusCacheModel.formInstanceRecordId =
			getFormInstanceRecordId();

		formSubmissionStatusCacheModel.seen = isSeen();

		Date seenDate = getSeenDate();

		if (seenDate != null) {
			formSubmissionStatusCacheModel.seenDate = seenDate.getTime();
		}
		else {
			formSubmissionStatusCacheModel.seenDate = Long.MIN_VALUE;
		}

		formSubmissionStatusCacheModel.companyId = getCompanyId();

		formSubmissionStatusCacheModel.groupId = getGroupId();

		formSubmissionStatusCacheModel.userId = getUserId();

		formSubmissionStatusCacheModel.userName = getUserName();

		String userName = formSubmissionStatusCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			formSubmissionStatusCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			formSubmissionStatusCacheModel.createDate = createDate.getTime();
		}
		else {
			formSubmissionStatusCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			formSubmissionStatusCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			formSubmissionStatusCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return formSubmissionStatusCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FormSubmissionStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FormSubmissionStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormSubmissionStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FormSubmissionStatus)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FormSubmissionStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FormSubmissionStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormSubmissionStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((FormSubmissionStatus)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FormSubmissionStatus>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FormSubmissionStatus.class, ModelWrapper.class);

	}

	private long _formSubmissionStatusId;
	private long _formInstanceRecordId;
	private boolean _seen;
	private Date _seenDate;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<FormSubmissionStatus, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FormSubmissionStatus)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"formSubmissionStatusId", _formSubmissionStatusId);
		_columnOriginalValues.put(
			"formInstanceRecordId", _formInstanceRecordId);
		_columnOriginalValues.put("seen", _seen);
		_columnOriginalValues.put("seenDate", _seenDate);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("formSubmissionStatusId", 1L);

		columnBitmasks.put("formInstanceRecordId", 2L);

		columnBitmasks.put("seen", 4L);

		columnBitmasks.put("seenDate", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FormSubmissionStatus _escapedModel;

}