/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ir.seydef.plugin.formcounter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import ir.seydef.plugin.formcounter.model.FormCounterRule;
import ir.seydef.plugin.formcounter.model.FormCounterRuleModel;
import ir.seydef.plugin.formcounter.model.FormCounterRuleSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FormCounterRule service. Represents a row in the &quot;FormCounterRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FormCounterRuleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormCounterRuleImpl}.
 * </p>
 *
 * @author S.Abolfazl Eftekhari
 * @see FormCounterRuleImpl
 * @generated
 */
@JSON(strict = true)
public class FormCounterRuleModelImpl
	extends BaseModelImpl<FormCounterRule> implements FormCounterRuleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form counter rule model instance should use the <code>FormCounterRule</code> interface instead.
	 */
	public static final String TABLE_NAME = "FormCounterRule";

	public static final Object[][] TABLE_COLUMNS = {
		{"formCounterRuleId", Types.BIGINT}, {"ruleName", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"ruleConditions", Types.VARCHAR},
		{"logicOperator", Types.VARCHAR}, {"active_", Types.BOOLEAN},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("formCounterRuleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ruleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ruleConditions", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("logicOperator", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FormCounterRule (formCounterRuleId LONG not null primary key,ruleName VARCHAR(75) null,description VARCHAR(75) null,ruleConditions VARCHAR(75) null,logicOperator VARCHAR(75) null,active_ BOOLEAN,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table FormCounterRule";

	public static final String ORDER_BY_JPQL =
		" ORDER BY formCounterRule.formCounterRuleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FormCounterRule.formCounterRuleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FORMCOUNTERRULEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static FormCounterRule toModel(FormCounterRuleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FormCounterRule model = new FormCounterRuleImpl();

		model.setFormCounterRuleId(soapModel.getFormCounterRuleId());
		model.setRuleName(soapModel.getRuleName());
		model.setDescription(soapModel.getDescription());
		model.setRuleConditions(soapModel.getRuleConditions());
		model.setLogicOperator(soapModel.getLogicOperator());
		model.setActive(soapModel.isActive());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<FormCounterRule> toModels(
		FormCounterRuleSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<FormCounterRule> models = new ArrayList<FormCounterRule>(
			soapModels.length);

		for (FormCounterRuleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public FormCounterRuleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _formCounterRuleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFormCounterRuleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _formCounterRuleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FormCounterRule.class;
	}

	@Override
	public String getModelClassName() {
		return FormCounterRule.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FormCounterRule, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FormCounterRule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormCounterRule, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FormCounterRule)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FormCounterRule, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FormCounterRule, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FormCounterRule)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FormCounterRule, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FormCounterRule, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FormCounterRule, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<FormCounterRule, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<FormCounterRule, Object>>();

		attributeGetterFunctions.put(
			"formCounterRuleId", FormCounterRule::getFormCounterRuleId);
		attributeGetterFunctions.put("ruleName", FormCounterRule::getRuleName);
		attributeGetterFunctions.put(
			"description", FormCounterRule::getDescription);
		attributeGetterFunctions.put(
			"ruleConditions", FormCounterRule::getRuleConditions);
		attributeGetterFunctions.put(
			"logicOperator", FormCounterRule::getLogicOperator);
		attributeGetterFunctions.put("active", FormCounterRule::getActive);
		attributeGetterFunctions.put(
			"companyId", FormCounterRule::getCompanyId);
		attributeGetterFunctions.put("groupId", FormCounterRule::getGroupId);
		attributeGetterFunctions.put("userId", FormCounterRule::getUserId);
		attributeGetterFunctions.put("userName", FormCounterRule::getUserName);
		attributeGetterFunctions.put(
			"createDate", FormCounterRule::getCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FormCounterRule::getModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<FormCounterRule, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<FormCounterRule, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<FormCounterRule, ?>>();

		attributeSetterBiConsumers.put(
			"formCounterRuleId",
			(BiConsumer<FormCounterRule, Long>)
				FormCounterRule::setFormCounterRuleId);
		attributeSetterBiConsumers.put(
			"ruleName",
			(BiConsumer<FormCounterRule, String>)FormCounterRule::setRuleName);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<FormCounterRule, String>)
				FormCounterRule::setDescription);
		attributeSetterBiConsumers.put(
			"ruleConditions",
			(BiConsumer<FormCounterRule, String>)
				FormCounterRule::setRuleConditions);
		attributeSetterBiConsumers.put(
			"logicOperator",
			(BiConsumer<FormCounterRule, String>)
				FormCounterRule::setLogicOperator);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<FormCounterRule, Boolean>)FormCounterRule::setActive);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FormCounterRule, Long>)FormCounterRule::setCompanyId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FormCounterRule, Long>)FormCounterRule::setGroupId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<FormCounterRule, Long>)FormCounterRule::setUserId);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FormCounterRule, String>)FormCounterRule::setUserName);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FormCounterRule, Date>)FormCounterRule::setCreateDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FormCounterRule, Date>)
				FormCounterRule::setModifiedDate);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getFormCounterRuleId() {
		return _formCounterRuleId;
	}

	@Override
	public void setFormCounterRuleId(long formCounterRuleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_formCounterRuleId = formCounterRuleId;
	}

	@JSON
	@Override
	public String getRuleName() {
		if (_ruleName == null) {
			return "";
		}
		else {
			return _ruleName;
		}
	}

	@Override
	public void setRuleName(String ruleName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ruleName = ruleName;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getRuleConditions() {
		if (_ruleConditions == null) {
			return "";
		}
		else {
			return _ruleConditions;
		}
	}

	@Override
	public void setRuleConditions(String ruleConditions) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ruleConditions = ruleConditions;
	}

	@JSON
	@Override
	public String getLogicOperator() {
		if (_logicOperator == null) {
			return "";
		}
		else {
			return _logicOperator;
		}
	}

	@Override
	public void setLogicOperator(String logicOperator) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logicOperator = logicOperator;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalActive() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("active_"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FormCounterRule.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FormCounterRule toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FormCounterRule>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FormCounterRuleImpl formCounterRuleImpl = new FormCounterRuleImpl();

		formCounterRuleImpl.setFormCounterRuleId(getFormCounterRuleId());
		formCounterRuleImpl.setRuleName(getRuleName());
		formCounterRuleImpl.setDescription(getDescription());
		formCounterRuleImpl.setRuleConditions(getRuleConditions());
		formCounterRuleImpl.setLogicOperator(getLogicOperator());
		formCounterRuleImpl.setActive(isActive());
		formCounterRuleImpl.setCompanyId(getCompanyId());
		formCounterRuleImpl.setGroupId(getGroupId());
		formCounterRuleImpl.setUserId(getUserId());
		formCounterRuleImpl.setUserName(getUserName());
		formCounterRuleImpl.setCreateDate(getCreateDate());
		formCounterRuleImpl.setModifiedDate(getModifiedDate());

		formCounterRuleImpl.resetOriginalValues();

		return formCounterRuleImpl;
	}

	@Override
	public int compareTo(FormCounterRule formCounterRule) {
		long primaryKey = formCounterRule.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FormCounterRule)) {
			return false;
		}

		FormCounterRule formCounterRule = (FormCounterRule)object;

		long primaryKey = formCounterRule.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FormCounterRule> toCacheModel() {
		FormCounterRuleCacheModel formCounterRuleCacheModel =
			new FormCounterRuleCacheModel();

		formCounterRuleCacheModel.formCounterRuleId = getFormCounterRuleId();

		formCounterRuleCacheModel.ruleName = getRuleName();

		String ruleName = formCounterRuleCacheModel.ruleName;

		if ((ruleName != null) && (ruleName.length() == 0)) {
			formCounterRuleCacheModel.ruleName = null;
		}

		formCounterRuleCacheModel.description = getDescription();

		String description = formCounterRuleCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			formCounterRuleCacheModel.description = null;
		}

		formCounterRuleCacheModel.ruleConditions = getRuleConditions();

		String ruleConditions = formCounterRuleCacheModel.ruleConditions;

		if ((ruleConditions != null) && (ruleConditions.length() == 0)) {
			formCounterRuleCacheModel.ruleConditions = null;
		}

		formCounterRuleCacheModel.logicOperator = getLogicOperator();

		String logicOperator = formCounterRuleCacheModel.logicOperator;

		if ((logicOperator != null) && (logicOperator.length() == 0)) {
			formCounterRuleCacheModel.logicOperator = null;
		}

		formCounterRuleCacheModel.active = isActive();

		formCounterRuleCacheModel.companyId = getCompanyId();

		formCounterRuleCacheModel.groupId = getGroupId();

		formCounterRuleCacheModel.userId = getUserId();

		formCounterRuleCacheModel.userName = getUserName();

		String userName = formCounterRuleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			formCounterRuleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			formCounterRuleCacheModel.createDate = createDate.getTime();
		}
		else {
			formCounterRuleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			formCounterRuleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			formCounterRuleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return formCounterRuleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FormCounterRule, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FormCounterRule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormCounterRule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FormCounterRule)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FormCounterRule, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FormCounterRule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormCounterRule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((FormCounterRule)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FormCounterRule>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FormCounterRule.class, ModelWrapper.class);

	}

	private long _formCounterRuleId;
	private String _ruleName;
	private String _description;
	private String _ruleConditions;
	private String _logicOperator;
	private boolean _active;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FormCounterRule, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FormCounterRule)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("formCounterRuleId", _formCounterRuleId);
		_columnOriginalValues.put("ruleName", _ruleName);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("ruleConditions", _ruleConditions);
		_columnOriginalValues.put("logicOperator", _logicOperator);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("formCounterRuleId", 1L);

		columnBitmasks.put("ruleName", 2L);

		columnBitmasks.put("description", 4L);

		columnBitmasks.put("ruleConditions", 8L);

		columnBitmasks.put("logicOperator", 16L);

		columnBitmasks.put("active_", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("groupId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FormCounterRule _escapedModel;

}