/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ir.seydef.plugin.formcounter.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import ir.seydef.plugin.formcounter.model.FormCounterRule;
import ir.seydef.plugin.formcounter.service.FormCounterRuleService;
import ir.seydef.plugin.formcounter.service.FormCounterRuleServiceUtil;
import ir.seydef.plugin.formcounter.service.persistence.FormCounterRulePersistence;
import ir.seydef.plugin.formcounter.service.persistence.FormSubmissionStatusPersistence;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the form counter rule remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link ir.seydef.plugin.formcounter.service.impl.FormCounterRuleServiceImpl}.
 * </p>
 *
 * @author S.Abolfazl Eftekhari
 * @see ir.seydef.plugin.formcounter.service.impl.FormCounterRuleServiceImpl
 * @generated
 */
public abstract class FormCounterRuleServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, FormCounterRuleService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FormCounterRuleService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FormCounterRuleServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		FormCounterRuleServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FormCounterRuleService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		formCounterRuleService = (FormCounterRuleService)aopProxy;

		FormCounterRuleServiceUtil.setService(formCounterRuleService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FormCounterRuleService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FormCounterRule.class;
	}

	protected String getModelClassName() {
		return FormCounterRule.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = formCounterRulePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected ir.seydef.plugin.formcounter.service.FormCounterRuleLocalService
		formCounterRuleLocalService;

	protected FormCounterRuleService formCounterRuleService;

	@Reference
	protected FormCounterRulePersistence formCounterRulePersistence;

	@Reference
	protected FormSubmissionStatusPersistence formSubmissionStatusPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		FormCounterRuleServiceBaseImpl.class);

}